# Generated by Django 5.1.1 on 2024-10-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
