services:
  backend:
    build:
      context: /Users/ebrahimgory/ecommerce_platform/Backend
    ports:
      - "8000:8000"
    volumes:
      - /Users/ebrahimgory/ecommerce_platform/Backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: /Users/ebrahimgory/ecommerce_platform/frontend
    ports:
      - "3000:3000"
    volumes:
      - /Users/ebrahimgory/ecommerce_platform/frontend:/app

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abcd-1234
      POSTGRES_DB: ecommerce_db
    ports:
      - "5433:5432"
